### ISSUE TITLE
MCU selection for remote io boards

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/pod-embedded#102]
Is there a better place for this? @ezraboley @rdaruwala Need to figure out what MCU/dev board we want to use for the remote IO boards. 

General asks from the hardware side of things:
1. Powered through the pins, rather than USB or a barrel jack
2. Small-ish form factor. These boards don't have a whole lot going on, so slapping a way over-specced controller would be a little silly. 
3. I2C interface
4. 3.3V or 5V logic ok. 5V preferred to be consistent with beaglebone. Please not 1.8V

**Comment by rdaruwala** [comment]
Moving forward with the STM32L432KC board (https://www.st.com/en/microcontrollers-microprocessors/stm32l432kc.html)
