### ISSUE TITLE
Install all build dependacies in deploy.sh

### ISSUE THREAD

**Issue by EUdds** [badgerloop-software/pod-embedded#128]
Add to the script so that cmake and other dependencies can be installed.

**Comment by EUdds** [comment]
1. Install python3 python3-pip python-is-python3
2. Install Cmake and gcc/g++
3. Auto run gtest-setup

**Comment by rdaruwala** [comment]
`clang-format` package too if you're looking for `./deploy.sh format` dependencies

Also - I think adding `./deploy format` to the "options" / "help" part of the script was omitted from the PR. May be worth amending here or elsewhere
