### ISSUE TITLE
Retro Sensors Drivers + Voting

### ISSUE THREAD

**Issue by rdaruwala** [badgerloop-software/pod-embedded#80]
Add retro drivers as well as voting logic to ensure that the `retroCount` value in the data structure is accurate

Data values to update:
- `time_t lastRetro1, lastRetro2, lastRetro3`
- `int retroCount`

**Comment by rdaruwala** [comment]
We'll also need to implement IMU checking + timer logic as described in the safety package

**Comment by ezraboley** [comment]
Im pretty far into this one on the `embedded-retro-dev` branch. There is a beaglebone GPIO API there along with code that captures the retro asynchronously. The only thing left is some wonky timestamp issues I was running into with the nanosecond counter, and the IMU checking

**Comment by ezraboley** [comment]
Voting is ready for testing, will test before merging in (and closing) the retro-dev branch

**Comment by ezraboley** [comment]
The voting _seems_ to be working, I'd like to do a full nav test though so that can be moved to a new issue
