### ISSUE TITLE
JSON library crashes with memory error

### ISSUE THREAD

**Issue by ezraboley** [badgerloop-software/pod-embedded#97]
The JSON library that we are using will run fine for some indeterminate amount of time before reliably crashing. It appears as if the error is memory allocation related, due to the allocator used by rapidJSON. 

There is a possible solution in either using a different allocator, changing how the document is created, or switching libraries. Either way, I would recommend using Valgrind or a similar tool to assess the damage and the fix so that we know this is no longer an issue. 

I will attach an error log when I can.

**Comment by rdaruwala** [comment]
Moving away from JSON this year, will be retiring this library
