### ISSUE TITLE
Better configuration 

### ISSUE THREAD

**Issue by ezraboley** [badgerloop-software/pod-embedded#98]
Something advisors mentioned was having a config file for quickly going into different run profiles (also something TUM had if you listened closely to their start up procedure). Having to change source code for things like number of retros to hit or the distance the pod should travel or timeouts all introduce unneeded failure points. 

An idea for this could be a python module that generates a list of #defines used throughout the program. Other solutions are welcome as well.

**Comment by rcastle1** [comment]
Confirmation of config files / current configuration parameters on the dashboard would also be good.
